Update imports to threejs r149
pmndrs/postprocessing pull request #448
Opened 2023-02-06 06:24 UTC by HexaField

The latest threejs (r149) seems to have removed the deprecated imports WebGLMultisampleRenderTarget and DataTexture3D so I have updated the imports and removed the related TODOS

2023-02-16 18:41 UTC, Jonathynlee commented
Hello, I need this update for a project I am working on, please approve ASAP! Thank you!

2023-02-19 05:32 UTC, AlexDaniel commented
I'm also interested in this 😇 Three has a lot of changes lately to the node system, not staying up to date feels scary :)

2023-02-19 21:54 UTC, vanruesc requested changes

2023-02-19 21:54 UTC, vanruesc commented on src/effects/LUT3DEffect.js
> - * TODO Replace DataTexture3D with Data3DTexture and rename inputEncoding to inputColorSpace.
Please revert the changes regarding `inputEncoding` (that's a planned breaking change for v7).

2023-02-19 21:54 UTC, vanruesc commented on src/textures/lut/LookupTexture.js
> -export class LookupTexture extends DataTexture3D {
- [ ] Update [postprocessing.d.ts](https://github.com/pmndrs/postprocessing/blob/main/types/postprocessing.d.ts#L8743)

2023-02-20 22:07 UTC, vanruesc approved these changes

2023-02-20 22:15 UTC, vanruesc commented
I've manually included the changes from this PR in the dev branch: 34bf4de

Thanks for contributing :+1:

2023-02-20 22:15 UTC, closed without merging